### ISSUE TITLE
Validator doesn't reconnect to supervisor

### ISSUE THREAD

**Issue by Stoner19** [herdius/herdius-core#1]
If for some reason a supervisor goes down, or the validator is started before there is a connection to the supervisor, the validator doesn't automatically try to reestablish a connection to the supervisor.

Additionally if there is disconnection between the validator and the supervisor, the supervisor is unable to load any further transactions/blocks using the `y` command.

**Comment by bittelc** [comment]
This issue was addressed and fixed in (Release 0.1.1](https://github.com/herdius/herdius-core/pull/7)
