### ISSUE TITLE
Broken pipe between validator and supervisor

### ISSUE THREAD

**Issue by Stoner19** [herdius/herdius-core#3]
As the current instructions are written, Supervisor should be running on port 3000 by default and the validator on 3001. With these instructions the validator connects to the supervisor without issue, but the supervisor is not able to able to load any blocks from file by pressing "y." The first time "y" is pressed nothing happens but after "y" is pressed a second time the Supervisor node results in the following error: 
```
4:54PM ERR stream: failed to write entire buffer error="write tcp <supervisor IP>:38332-><validator IP>:3001: write: connection reset by peer"
4:54PM ERR stream: failed to write entire buffer error="write tcp <supervisor IP>:38332-><validator IP>:3001: write: connection reset by peer"
4:54PM WRN %!s(<nil>) error="write tcp <supervisor IP>:38332-><validator IP>:3001: write: connection reset by peer"
```

HOWEVER, If the validator is started with port 3000 `make start-validator PORT=3000 PEERS="tcp://<supervisor IP>:3000" HOST="<validator IP>"` the supervisor is able to write blocks by pressing "y" the first time and on the validator we see `:58PM INF <tcp://127.0.0.1:3000> #Txs: 500`, but the second time "y" is pressed on the supervisor this error results on the validator:
```
5:58PM INF <tcp://127.0.0.1:3000> #Txs: 500
5:58PM ERR stream: failed to write entire buffer error="write tcp 127.0.0.1:57254->127.0.0.1:3000: write: broken pipe"
5:58PM WRN failed to send message to peer error="stream: failed to write to socket: write tcp 127.0.0.1:57254->127.0.0.1:3000: write: broken pipe" peer_id={"address":"tcp://127.0.0.1:3000","id":"5JldaYaC0vRJlN3bnAy2jJtsGBVs4/glkgMxljIGPWI=","public_key":"fuVe5CDj8uxuUfFJafhEsJT+v4MqIQla0E0GkiCXGSI2/zz+RQ=="}
5:58PM WRN %!s(<nil>) error="write tcp 127.0.0.1:57254->127.0.0.1:3000: write: broken pipe"
```

**Comment by bittelc** [comment]
I've been unable to reproduce this issue. We've likely addressed the issue, but if you find that you've run into another occurrence, please open this back up and provide as much detail as possible on how we can reproduce it.
