### ISSUE TITLE
Improper validator counting

### ISSUE THREAD

**Issue by bittelc** [herdius/herdius-core#52]
In order for a `ChildBlock` to be approved to be nested in the `BaseBlock` by the Supervisor, the number of `vote`s must equal the number of Validators in the pool.

Frequently, the Supervisor improperly counts the number of Validators. In the below example, I am running a single Supervisor and a single Validator:

```
Received child block message from validator
3:54PM INF <tcp://127.0.0.1:3002> Validator verified and signed the child block: true
3:54PM INF Vote count mismatch, votes (1) of validators (2)
```

**Comment by kanishkatn** [comment]
Hi, I will work on this

I am having a bit of a problem setting it up on my local though. When I start the validator with the command 

`make start-validator PORT=3001 PEERS="tcp://127.0.0.1:3000" HOST="127.0.0.1"`

I get an error saying 

`unable to get supervisor client: network: peer should not dial itself`

Can someone please help me with this?

**Comment by lmahanand** [comment]
Hello @kanishkatn , Apologies in getting back to you late on your query. You need to make a manual change in Makefile at this line **67** https://github.com/herdius/herdius-core/blob/master/Makefile#L67.

replace @$(GORUN) `cmd/herserver/main.go$(GOPARAMETERS)` to `@$(GORUN) cmd/herserver/main.go$(GOPARAMETERS) -port=3001`. It will start the validator listening at 3001. Same way in case you need to start more validators, assign a different or a port not in use.

Please also make sure you have the API keys exported. [Api key detail](https://github.com/herdius/herdius-core#secret-store-and-retrieval)

**Comment by kanishkatn** [comment]
Thanks @lmahanand. I will check it out

Can you please tell me how I can get this value BLOCKCHAIN_INFO_KEY?

**Comment by niktrix** [comment]
https://api.blockchain.info/customer/sign

use this for to create Blockchaininfo key

**Comment by kanishkatn** [comment]
Thank you so much :)
